### ISSUE TITLE
图形缩小后报错

### ISSUE THREAD

**Issue by 520MianXiangDuiXiang520** [le5le-com/topology#185]
您好，我在本地使用 topology-vue 时，发现将一个图形缩小（比如把一个矩形缩成 “一条线” ）后会报下面这个错误：

```
topology-vue.umd.js?bd5c:64930 Uncaught DOMException: Failed to execute 'arcTo' on 'CanvasRenderingContext2D': The radius provided (-7) is negative.
    at Object.rectangle (webpack-internal:///./node_modules/topology-vue/topology-vue.umd.js:64925:9)
    at Node.fb15.Node.draw (webpack-internal:///./node_modules/topology-vue/topology-vue.umd.js:67691:31)
    at Node.fb15.Pen.render (webpack-internal:///./node_modules/topology-vue/topology-vue.umd.js:64727:14)
    at Offscreen.fb15.Offscreen.render (webpack-internal:///./node_modules/topology-vue/topology-vue.umd.js:68522:18)
    at Topology.fb15.Topology.render (webpack-internal:///./node_modules/topology-vue/topology-vue.umd.js:71331:24)
    at eval (webpack-internal:///./node_modules/topology-vue/topology-vue.umd.js:70596:23)
rectangle @ topology-vue.umd.js?bd5c:64930
fb15.Node.draw @ topology-vue.umd.js?bd5c:67696
fb15.Pen.render @ topology-vue.umd.js?bd5c:64732
fb15.Offscreen.render @ topology-vue.umd.js?bd5c:68527
fb15.Topology.render @ topology-vue.umd.js?bd5c:71336
eval @ topology-vue.umd.js?bd5c:70601
requestAnimationFrame (async)
Topology.onMouseMove @ topology-vue.umd.js?bd5c:70461
divLayer.canvas.onmousemove @ topology-vue.umd.js?bd5c:71118
```
![image](https://user-images.githubusercontent.com/44747536/117840080-68f6f200-b2ae-11eb-9bec-42e6922adb5b.png)

下面是导出后的 json 数据，但这些数据导入示例网站是没问题的，请问这该如何解决

```json
{
  "pens": [
    {
      "imageRatio": true,
      "animateDuration": 0,
      "animateFrames": [],
      "animateFrame": 0,
      "name": "rectangle",
      "tags": [],
      "visible": true,
      "rect": {
        "x": 218,
        "y": 151,
        "width": 67,
        "height": -14,
        "center": { "x": 251.5, "y": 144 },
        "ex": 285,
        "ey": 137
      },
      "fontColor": "#222222",
      "fontFamily": "\"Hiragino Sans GB\", \"Microsoft YaHei\", \"Helvetica Neue\", Helvetica, Arial",
      "fontSize": 12,
      "lineHeight": 1.5,
      "fontStyle": "normal",
      "fontWeight": "normal",
      "textAlign": "center",
      "textBaseline": "middle",
      "textBackground": "",
      "events": [],
      "dash": 0,
      "lineDashOffset": 0,
      "lineWidth": 1,
      "strokeStyle": "#222222",
      "fillStyle": "",
      "globalAlpha": 1,
      "rotate": 0,
      "offsetRotate": 0,
      "textMaxLine": 0,
      "textOffsetX": 0,
      "textOffsetY": 0,
      "animatePos": 0,
      "id": "67ede4f",
      "zRotate": 0,
      "borderRadius": 0,
      "imageAlign": "center",
      "gradientAngle": 0,
      "gradientRadius": 0.01,
      "paddingTop": 10,
      "paddingBottom": 10,
      "paddingLeft": 10,
      "paddingRight": 10,
      "text": "正方形",
      "icon": "",
      "iconFamily": "topology",
      "iconColor": "#2f54eb",
      "type": 0,
      "animateType": "",
      "paddingLeftNum": 10,
      "paddingRightNum": 10,
      "paddingTopNum": 10,
      "paddingBottomNum": 10,
      "textRect": {
        "x": 194,
        "y": 161,
        "width": 81,
        "height": -34,
        "center": { "x": 234.5, "y": 144 },
        "ex": 275,
        "ey": 127
      },
      "fullTextRect": {
        "x": 228,
        "y": 161,
        "width": 47,
        "height": -34,
        "center": { "x": 251.5, "y": 144 },
        "ex": 275,
        "ey": 127
      },
      "iconRect": {
        "x": 228,
        "y": 161,
        "width": -34,
        "height": -34,
        "center": { "x": 211, "y": 144 },
        "ex": 194,
        "ey": 127
      },
      "fullIconRect": {
        "x": 228,
        "y": 161,
        "width": 47,
        "height": -34,
        "center": { "x": 251.5, "y": 144 },
        "ex": 275,
        "ey": 127
      }
    }
  ],
  "lineName": "curve",
  "fromArrow": "",
  "toArrow": "triangleSolid",
  "scale": 1,
  "locked": 0,
  "websocket": "",
  "mqttUrl": "",
  "component": false,
  "mqttOptions": { "clientId": "47ec7e40" }
}

```

**Comment by 520MianXiangDuiXiang520** [comment]
抱歉，原因是我使用了一个较低的版本
